config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home/about'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index,:show]
  before_action :correct_user, only:[:edit,:update,:destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this friend" if @friend.nil?

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :reddit, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    @about_me = "My name is palmtrees"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block"%>
    <%= form.text_field :first_name, class:"form-control",:required => true, placeholder:"First Name" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block"%>
    <%= form.text_field :last_name, placeholder:"Last Name", class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, placeholder:"Email", class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, placeholder:"Phone", class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :reddit, style: "display: block" %>
    <%= form.text_field :reddit, placeholder:"Reddit", class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.number_field :user_id, id: :friend_user_id, value:current_user.id, type: :hidden, class:"form-control" %>
  </div>

  <br>
  <div class="form-group">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= friend.first_name %>
    <%= friend.last_name %>
  </h1>
  <p class="lead">
    <%= friend.email %>  | 
    <%= friend.phone %>  |  
    <%= friend.reddit %>

  </p>
  <br/>

  <%= link_to 'Edit', edit_friend_path(friend), class:"btn btn-secondary" %>

<%= link_to 'Delete', friend, method: :delete, data: { "turbo-method": :delete }, class: "btn btn-danger" %>
   
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-primary" %>
  <%= link_to "Delete", @friend, data: { "turbo-method": :delete }, class:"btn btn-danger" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <div id="friends">
    <table class ="table table-striped table-hover">
    <thead class = thead-dark>
      <th scope="col">Name </th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Reddit</th>
      <th scope="col"></th>
    </thead>
    <tbody>
    <% @friends.each do |friend| %>
    <% if friend.user == current_user%>
      <tr>
        <td scope="row">
        <%=link_to friend.first_name + ' ' + friend.last_name ,friend%>
        <td><%= friend.email%></td>
        <td><%= friend.phone%></td>
        <td><%= friend.reddit%></td>
        <td><%=link_to "Delete",friend, data: { "turbo-method": :delete }, class:"btn btn-outline-danger btn-sm"%></td>
      </tr>
    <%end%>
    <% end %>
    </tbody>
    </table>
  </div>

  <%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>
<%else%>
  <h1>This is my Rails page</h1>
Hello World!
<%end%>

app/views/friends/new.html.erb
<br>
<div class="card">
  <div class="card-header">
    <h1>Add New friend</h1>
  </div>
  <div class="card-body">
    <br>
      <%= render "form", friend: @friend %>
    <br>
    <div>
      <%= link_to "Back to friends", friends_path, class: "btn btn-dark" %>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>  | 
    <%= @friend.phone %>  |  
    <%= @friend.reddit %>

  </p>
  <br/>

  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>

<%= link_to 'Delete', @friend, data: { "turbo-method": :delete }, class: "btn btn-danger" %>
   
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

</div>

app/views/home/_header.html.erb
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="nav-home-tab" data-toggle="tab" data-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">
        <%= link_to 'Friend App', root_path, class: "navbar-brand"%>
    </button>
    
    <button class="nav-link" id="nav-contact-tab" data-toggle="tab" data-target="#nav-contact" type="button" role="tab" 
    aria-controls="nav-contact" aria-selected="false"> 
      <%= link_to 'About Us', home_about_path, class:"nav-link"%> 
    </button>
   
    <% if user_signed_in? %>
    <button class="nav-link" id="nav-profile-tab" data-toggle="tab" data-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</button>
    <button class="nav-link" id="nav-contact-tab" data-toggle="tab" data-target="#nav-contact" type="button" role="tab" 
    aria-controls="nav-contact" aria-selected="false"> 
      <%= link_to 'New Friend', new_friend_path, class:"nav-link"%> 
    </button>
      <button class="nav-link" id="nav-contact-tab" data-toggle="tab" data-target="#nav-contact" type="button" role="tab" 
      aria-controls="nav-contact" aria-selected="false"> 
        <%= link_to 'Sign Out', destroy_user_session_path,:method => :delete, class:"nav-link"%> 
      </button>
      <button class="nav-link" id="nav-contact-tab" data-toggle="tab" data-target="#nav-contact" type="button" role="tab" 
      aria-controls="nav-contact" aria-selected="false"> 
        <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%> 
      </button>
    <%else%>
      <button class="nav-link" id="nav-contact-tab" data-toggle="tab" data-target="#nav-contact" type="button" role="tab" 
      aria-controls="nav-contact" aria-selected="false"> 
        <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%> 
      </button>
      <button class="nav-link" id="nav-contact-tab" data-toggle="tab" data-target="#nav-contact" type="button" role="tab" 
      aria-controls="nav-contact" aria-selected="false"> 
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%> 
      </button>
    <%end%>
  </div>
</nav>
<br>

app/views/home/about.html.erb
<h1>About Us</h1>

<p>
    <%= @about_me%>
</p>

app/views/home/index.html.erb
<h1>This is my Rails page</h1>
Hello World!

app/views/layouts/_alerts.html.erb
<br>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
  <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    
  </head>

  <body>
    <%= render 'home/header'%>
    <div class="container">
    <%if notice%>
      <%=render 'layouts/alerts'%>
    <%end%>
        <%= yield %>
      <br>
     
    </div>
  </body>
</html>